# Generated by Django 3.1.7 on 2021-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_delivery_is_admin_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='driving_licence',
        ),
        migrations.AddField(
            model_name='delivery',
            name='driving_license',
            field=models.ImageField(null=True, upload_to='DrivingLicenseDelivery/'),
        ),
    ]
