# Generated by Django 3.1.7 on 2021-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210428_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
