# Generated by Django 3.1.7 on 2021-05-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_seller_is_admin_verified'),
        ('Product', '0004_auto_20210508_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Seller.seller'),
        ),
    ]
