# Generated by Django 3.1.7 on 2021-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='id_proof',
            field=models.ImageField(null=True, upload_to='IdProofSeller/'),
        ),
    ]
