# Generated by Django 3.1.7 on 2021-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_seller_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
