# Generated by Django 3.1.7 on 2021-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210527_1301'),
        ('Order', '0007_auto_20210528_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='productOrdered', to='Product.Product'),
        ),
    ]
